"""Tests for the RecommendationInfo descriptor model and the HERO folder type."""

from __future__ import annotations

from dataclasses import fields

from music_assistant_models.enums import RecommendationFolderType
from music_assistant_models.media_items import RecommendationInfo


def test_recommendation_folder_type_has_hero() -> None:
    """The hero render style is available and serializes to its string value."""
    assert RecommendationFolderType.HERO == "hero"
    assert RecommendationFolderType("hero") is RecommendationFolderType.HERO
    # existing members still present
    assert RecommendationFolderType.DEFAULT == "default"
    assert RecommendationFolderType.TIMELINE == "timeline"


def test_recommendation_info_defaults_and_uri() -> None:
    """A minimal RecommendationInfo fills sensible defaults and an auto uri."""
    info = RecommendationInfo(
        item_id="recently_played",
        provider="library",
        name="Recently played",
        icon="mdi-motion-play",
    )
    assert info.enabled_by_default is True
    assert info.type is RecommendationFolderType.DEFAULT
    assert info.category is None
    assert info.is_playable is False
    assert info.uri is not None  # auto-generated by the base __post_init__


def test_recommendation_info_has_no_items_field() -> None:
    """RecommendationInfo is the lean descriptor: it must NOT carry an items list."""
    field_names = {f.name for f in fields(RecommendationInfo)}
    assert "items" not in field_names


def test_recommendation_info_roundtrip() -> None:
    """RecommendationInfo serializes and deserializes losslessly via mashumaro."""
    info = RecommendationInfo(
        item_id="top_picks",
        provider="library",
        name="Top Picks for You",
        icon="mdi-star",
        subtitle="A mix just for you",
        enabled_by_default=False,
        type=RecommendationFolderType.HERO,
        category="made_for_you",
    )
    data = info.to_dict()
    assert data["enabled_by_default"] is False
    assert data["type"] == "hero"
    assert data["category"] == "made_for_you"
    assert "items" not in data
    restored = RecommendationInfo.from_dict(data)
    assert restored == info


def test_recommendation_info_effective_enabled_field() -> None:
    """RecommendationInfo carries an effective per-user `enabled` flag (default True)."""
    info = RecommendationInfo(item_id="x", provider="library", name="X")
    assert info.enabled is True
    assert info.to_dict()["enabled"] is True
    disabled = RecommendationInfo(item_id="y", provider="library", name="Y", enabled=False)
    assert RecommendationInfo.from_dict(disabled.to_dict()).enabled is False
